### ISSUE TITLE
Does not work on pypy 3.10

### ISSUE THREAD

**Issue by muraj238** [uriyyo/async-eval#195]
Hi. The package doesn't work with pypy 3.10. 
It crashes on the save_locals() function with AttributeError: module 'ctypes' has no attribute 'pythonapi'.
When I comment that line, it seems to work ok, so it could not be hard to fix, but I don't understand function's purpose.

**Comment by uriyyo** [comment]
Hi @muraj238,

It's used to save state of locals to frame. It might be not required for pypy. I will take a look.

**Comment by uriyyo** [comment]
Hi @muraj238,

This issue should be fixed in version `0.3.1`.
